### ISSUE TITLE
width / height attributes

### ISSUE THREAD

**Issue by pbeyani** [NikolajDL/Excolo-Slider#16]
Hi, 

Is there anyway to set the width and heigh of the slider with pure css and not within the initialisation options? Or can you set the width or height to be 'auto' in the initialisation?I've tried, but it seems to cause problems.

Cheers

**Comment by alvordr** [comment]
I have the same problem, but it's more complex.  I'm not using it solely for images, but for content...like an announcements slider, which should show within separate <divs> various content.  If I turn autoSize to false, it allows me to adjust the height, but I never know what the max height will be.  I'm letting another user edit the content.  How do I solve this?  If I put the height to 100%, it simply shows all the slides vertically, as if there is no slider.
